version: '3'
services:
  flask:
     build: .
     image: virus:v1
     ports:
       - "80:5000"
     volumes:
       - "./uploads:/app/uploads"
       - "./server.log:/app/server.log"
     restart: always
     container_name: virus